# Stage 1: Build the application
# Use an official Maven image as the base image
FROM maven:3.9.8-eclipse-temurin-21 AS build
# Set the working directory in the container
WORKDIR /service-registry
# copy project files to the container
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre AS runtime
WORKDIR /service-registry
# Copy the built JAR file from the previous stage to the container
COPY --from=build /service-registry/target/service-registry-0.0.1-SNAPSHOT.jar service-registry.jar
# Set the command to run the application
ENTRYPOINT ["java", "-jar", "service-registry.jar"]