# Stage 1: Build the application
# Use an official Maven image as the base image
FROM maven:3.9.8-eclipse-temurin-21 AS build
# Set the working directory in the container
WORKDIR /user-service
# copy project files to the container
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre AS runtime
WORKDIR /user-service
# Copy the built JAR file from the previous stage to the container
COPY --from=build /user-service/target/user-service-0.0.1-SNAPSHOT.jar user-service.jar
# Set the command to run the application
ENTRYPOINT ["java", "-jar", "user-service.jar"]